# Generated by Django 3.0.8 on 2020-07-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('bankName',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=500, unique=True)),
                ('branchAddress', models.CharField(max_length=500)),
                ('branchCity', models.CharField(max_length=500)),
                ('branchDistrict', models.CharField(max_length=500)),
                ('branchState', models.CharField(max_length=500)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bank')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ('branchName',),
            },
        ),
    ]
