# Generated by Django 3.0.8 on 2020-07-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200703_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bank_name',
            new_name='bank',
        ),
    ]
